In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
a = np.array([0, 1, 2, 3])

In [17]:
a.ndim

1

In [18]:
a.shape

(4,)

In [19]:
len(a)

4

In [20]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [21]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b.ndim

2

In [23]:
b.shape

(2, 3)

In [24]:
len(b)

2

In [26]:
c = np.array([[[1], [2]], [[3], [4]]])

In [27]:
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [28]:
c.shape

(2, 2, 1)

In [29]:
d = np.array([[7, 5, 3, 1], [6, 4, 2, 0]])

In [30]:
len(d)

2

In [31]:
d.shape

(2, 4)

In [32]:
d.ndim

2

In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [42]:
c = np.linspace(0, 1, 21)
c

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])